Improve the install script by installing PHP and Nginx out of the box

diff --git a/installscript b/installscript
--- a/installscript
+++ b/installscript
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Install some basic system requirements
-apt install curl fontconfig php -y
+apt install curl fontconfig wget nginx -y
 
 # Symlink bashrc
 ln -s $HOME/.dotfiles/shell/.bashrc $HOME/.bashrc
@@ -30,13 +30,31 @@ cd $HOME/.dotfiles
 echo 'reset the .bashrc file due to changes by the NVM install'
 git checkout HEAD -- shell/.bashrc
 
+echo 'Install PHP'
+echo '-----------'
+sudo apt install php php-dev php-fpm
+
 echo 'Install composer'
 echo '----------------'
-wget https://getcomposer.org/composer.phar
-mv composer.phar /usr/local/bin/composer
-rm composer.phar
+EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
+php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
+then
+    >&2 echo 'ERROR: Invalid installer checksum'
+    rm composer-setup.php
+    exit 1
+fi
+php composer-setup.php
+rm composer-setup.php
+sudo mv composer.phar /usr/local/bin/composer
+sudo chmod 755 /usr/local/bin/composer
 
 echo 'Install redis'
 echo '-------------'
 sudo apt install redis
+
+echo 'Install Nginx'
+echo '-------------'
+sudo apt install nginx
 
